### ISSUE TITLE
TypeError: object.__init__() takes exactly one argument (the instance to initialize)

### ISSUE THREAD

**Issue by KeyC-code** [kivy-garden/garden.tickline#10]
Traceback (most recent call last):
   File "d:\свалка\metal-bot\garden.roulette-master\__init__.py", line 476, in <module>
     b.add_widget(Roulette(density=2.8, selected_value=2013))
   File "d:\свалка\metal-bot\garden.roulette-master\__init__.py", line 336, in __init__
     super(Roulette, self).__init__(**kw)
   File "C:\Users\alexk\.kivy\garden\garden.tickline\__init__.py", line 568, in __init__
     self.on_scroll_effect_cls()
   File "C:\Users\alexk\.kivy\garden\garden.tickline\__init__.py", line 614, in on_scroll_effect_cls
     effect = self.scroll_effect = self.scroll_effect_cls(round_value=False)
   File "C:\Users\alexk\AppData\Local\Programs\Python\Python39\lib\site-packages\kivy\effects\kinetic.py", line 120, in __init__
     super(KineticEffect, self).__init__(**kwargs)
   File "kivy\_event.pyx", line 245, in kivy._event.EventDispatcher.__init__
 TypeError: object.__init__() takes exactly one argument (the instance to initialize)
PS D:\свалка\metal-bot\garden.roulette-master>

**Comment by AleRamone** [comment]
Hi! have you been able to solve this? i got the same problem.
